[package]
authors = ["Paho Lurie-Gregg <paho.luriegregg@outreach.io>"]
edition = "2018"
name = "listentothis-playlist"
version = "0.1.0"
[dependencies]
dotenv = "*"
dotenv_codegen = "*"
failure = "*"
htmlescape = "*"
regex = "*"
reqwest = "*"
serde_json = "*"

[dependencies.serde]
features = ["derive"]
version = "*"
